name: Node Request
description: Request a new node to be added to the library
type: "Task"
projects: ["griptape-ai/2"]
labels: ["nodes"]
body:
  - type: markdown
    attributes:
      value: |
        # Node Request
        Thank you for taking the time to fill out this node request.
        Please provide as much information as possible to help us process your request quickly.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the node and what you would like it to do
      placeholder: |
        What kind of node do you want to add?
        What functionality should it have?
        What is the use case for this node?
    validations:
      required: true

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: If applicable, what are you doing now to reproduce the functionality of this node?
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop images here
    validations:
      required: false

  - type: input
    id: video
    attributes:
      label: Video Link
      description: If applicable, provide a link to a video demonstrating the issue
      placeholder: e.g., https://www.loom.com/share/your-video-id
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful
    validations:
      required: false
