from __future__ import annotations

import json
import logging
from http import HTTPStatus
from typing import Any

import httpx
from griptape.artifacts import ImageUrlArtifact

from griptape_nodes.exe_types.core_types import Parameter, ParameterMode
from griptape_nodes.exe_types.param_components.seed_parameter import SeedParameter
from griptape_nodes.traits.options import Options
from griptape_nodes_library.base_proxy_node import GriptapeProxyNode

logger = logging.getLogger("griptape_nodes")

__all__ = ["QwenImageGeneration"]

# Size options (Qwen's available resolutions)
SIZE_OPTIONS = ["1328*1328", "1664*928", "1472*1140", "1140*1472", "928*1664"]

# Model options
MODEL_OPTIONS = ["qwen-image", "qwen-image-plus"]


class QwenImageGeneration(GriptapeProxyNode):
    """Generate images using Qwen models via Griptape model proxy.

    Documentation: https://www.alibabacloud.com/help/en/model-studio/qwen-image-api

    Inputs:
        - model (str): Qwen model to use ("qwen-image" or "qwen-image-plus", default: "qwen-image")
        - prompt (str): Text description of the desired image (max 800 characters)
        - size (str): Output image resolution (default: "1328*1328")
            Available sizes: 1328*1328 (1:1), 1664*928 (16:9), 1472*1140 (4:3), 1140*1472 (3:4), 928*1664 (9:16)
        - randomize_seed (bool): If true, randomize the seed on each run
        - seed (int): Random seed for reproducible results (default: 42)
        - prompt_extend (bool): Enable intelligent prompt rewriting to improve quality (adds 3-4s, default: False)
        - watermark (bool): Add "Generated by Qwen-Image" watermark in lower-right corner (default: False)

    Outputs:
        - generation_id (str): Generation ID from the API
        - provider_response (dict): Verbatim provider response from the model proxy
        - image_url (ImageUrlArtifact): Generated image as URL artifact
        - was_successful (bool): Whether the generation succeeded
        - result_details (str): Details about the generation result or error
    """

    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        self.category = "API Nodes"
        self.description = "Generate images using Qwen models via Griptape model proxy"

        # Model selection
        self.add_parameter(
            Parameter(
                name="model",
                input_types=["str"],
                type="str",
                default_value="qwen-image",
                tooltip="Select the Qwen model to use",
                allowed_modes={ParameterMode.INPUT, ParameterMode.PROPERTY},
                traits={Options(choices=MODEL_OPTIONS)},
            )
        )

        # Core parameters
        self.add_parameter(
            Parameter(
                name="prompt",
                input_types=["str"],
                type="str",
                tooltip="Text description of the desired image",
                allowed_modes={ParameterMode.INPUT, ParameterMode.PROPERTY},
                ui_options={
                    "multiline": True,
                    "placeholder_text": "Describe the image you want to generate...",
                    "display_name": "Prompt",
                },
            )
        )

        # Size parameter
        self.add_parameter(
            Parameter(
                name="size",
                input_types=["str"],
                type="str",
                default_value="1328*1328",
                tooltip="Output image resolution (1328*1328=1:1, 1664*928=16:9, 1472*1140=4:3, 1140*1472=3:4, 928*1664=9:16)",
                allowed_modes={ParameterMode.INPUT, ParameterMode.PROPERTY},
                traits={Options(choices=SIZE_OPTIONS)},
            )
        )

        # Prompt extend parameter (Qwen's version of prompt upsampling)
        self.add_parameter(
            Parameter(
                name="prompt_extend",
                input_types=["bool"],
                type="bool",
                default_value=False,
                tooltip="Enable intelligent prompt rewriting to improve generation quality (adds 3-4 seconds)",
                allowed_modes={ParameterMode.INPUT, ParameterMode.PROPERTY},
            )
        )

        # Watermark parameter
        self.add_parameter(
            Parameter(
                name="watermark",
                input_types=["bool"],
                type="bool",
                default_value=False,
                tooltip="Add 'Generated by Qwen-Image' watermark in lower-right corner",
                allowed_modes={ParameterMode.INPUT, ParameterMode.PROPERTY},
            )
        )

        # Initialize SeedParameter component (at the bottom of input parameters)
        self._seed_parameter = SeedParameter(self)
        self._seed_parameter.add_input_parameters()

        # OUTPUTS
        self.add_parameter(
            Parameter(
                name="generation_id",
                output_type="str",
                tooltip="Generation ID from the API",
                allowed_modes={ParameterMode.OUTPUT},
                ui_options={"hide_property": True},
            )
        )

        self.add_parameter(
            Parameter(
                name="provider_response",
                output_type="dict",
                type="dict",
                tooltip="Verbatim response from Griptape model proxy",
                allowed_modes={ParameterMode.OUTPUT},
                ui_options={"hide_property": True},
            )
        )

        self.add_parameter(
            Parameter(
                name="image_url",
                output_type="ImageUrlArtifact",
                type="ImageUrlArtifact",
                tooltip="Generated image as URL artifact",
                allowed_modes={ParameterMode.OUTPUT, ParameterMode.PROPERTY},
                settable=False,
                ui_options={"is_full_width": True, "pulse_on_run": True},
            )
        )

        # Create status parameters for success/failure tracking (at the end)
        self._create_status_parameters(
            result_details_tooltip="Details about the image generation result or any errors",
            result_details_placeholder="Generation status and details will appear here.",
            parameter_group_initially_collapsed=False,
        )

    def _get_api_model_id(self) -> str:
        """Get the API model ID for this generation."""
        return self.get_parameter_value("model") or "qwen-image"

    async def _build_payload(self) -> dict[str, Any]:
        """Build the request payload for Qwen image generation."""
        # Preprocess seed parameter
        self._seed_parameter.preprocess()

        prompt = self.get_parameter_value("prompt")
        size = self.get_parameter_value("size")
        seed = self._seed_parameter.get_seed()
        prompt_upsampling = self.get_parameter_value("prompt_extend")
        watermark = self.get_parameter_value("watermark")

        # Build content array with text prompt
        content = [{"text": prompt}]

        # Flatten structure - parameters should be at top level for MultiModalConversation.call()
        payload = {
            "messages": [{"role": "user", "content": content}],
            "size": size,
            "prompt_extend": prompt_upsampling,
            "watermark": watermark,
            "seed": seed,
            "n": 1,
        }

        return payload

    async def _parse_result(self, result_json: dict[str, Any], generation_id: str) -> None:
        """Parse Qwen result and extract image.

        Response shape:
        {
            "status_code": 200,
            "request_id": "...",
            "output": {
                "choices": [
                    {
                        "message": {
                            "content": [
                                {"image": "https://..."}
                            ]
                        }
                    }
                ]
            }
        }
        """
        # Check status_code
        status_code = result_json.get("status_code")
        if status_code and status_code != HTTPStatus.OK:
            logger.error("Generation failed with status_code: %s", status_code)
            self._set_safe_defaults()
            error_details = self._extract_error_message(result_json)
            self._set_status_results(was_successful=False, result_details=error_details)
            return

        # Extract image URL from result_json.choices[0].message.content[0].image
        try:
            choices = result_json.get("choices", [])
            choice = choices[0]
            message = choice.get("message", {})
            content = message.get("content", [])
            first_content_item = content[0]
            image_url = first_content_item.get("image")
        except Exception as e:
            logger.error("Failed to extract image URL from response: %s", e)
            self._set_safe_defaults()
            self._set_status_results(
                was_successful=False,
                result_details="Generation completed but no content found in the response.",
            )
            return

        if image_url:
            await self._save_image_from_url(image_url, generation_id)
        else:
            logger.warning("No image URL found in content")
            self._set_safe_defaults()
            self._set_status_results(
                was_successful=False,
                result_details="Generation completed but no image URL was found in the response.",
            )

    async def _save_image_from_url(self, image_url: str, generation_id: str) -> None:
        """Download and save the image from the provided URL."""
        from griptape_nodes.retained_mode.griptape_nodes import GriptapeNodes

        try:
            logger.info("Downloading image from URL")
            image_bytes = await self._download_bytes_from_url(image_url)
            if image_bytes:
                filename = f"qwen_image_{generation_id}.jpg"
                static_files_manager = GriptapeNodes.StaticFilesManager()
                saved_url = static_files_manager.save_static_file(image_bytes, filename)
                self.parameter_output_values["image_url"] = ImageUrlArtifact(value=saved_url, name=filename)
                logger.info("Saved image to static storage as %s", filename)
                self._set_status_results(
                    was_successful=True, result_details=f"Image generated successfully and saved as {filename}."
                )
            else:
                self.parameter_output_values["image_url"] = ImageUrlArtifact(value=image_url)
                self._set_status_results(
                    was_successful=True,
                    result_details="Image generated successfully. Using provider URL (could not download image bytes).",
                )
        except Exception as e:
            logger.error("Failed to save image from URL: %s", e)
            self.parameter_output_values["image_url"] = ImageUrlArtifact(value=image_url)
            self._set_status_results(
                was_successful=True,
                result_details=f"Image generated successfully. Using provider URL (could not save to static storage: {e}).",
            )

    def _extract_error_message(self, response_json: dict[str, Any]) -> str:
        """Extract error message from failed generation response.

        Args:
            response_json: The JSON response from the generation status endpoint

        Returns:
            str: A formatted error message to display to the user
        """
        # Try to extract from provider response (Qwen-specific legacy pattern)
        parsed_provider_response = self._parse_provider_response(response_json.get("provider_response"))
        if parsed_provider_response:
            provider_error = parsed_provider_response.get("error")
            if provider_error:
                top_level_error = response_json.get("error")
                provider_error_msg = self._format_provider_error(parsed_provider_response, top_level_error)
                if provider_error_msg:
                    return provider_error_msg

        # Fall back to standard error extraction
        return super()._extract_error_message(response_json)

    def _parse_provider_response(self, provider_response: Any) -> dict[str, Any] | None:
        """Parse provider_response if it's a JSON string."""
        if isinstance(provider_response, str):
            try:
                return json.loads(provider_response)
            except Exception:
                return None
        if isinstance(provider_response, dict):
            return provider_response
        return None

    def _format_provider_error(
        self, parsed_provider_response: dict[str, Any] | None, top_level_error: Any
    ) -> str | None:
        """Format error message from parsed provider response."""
        if not parsed_provider_response:
            return None

        provider_error = parsed_provider_response.get("error")
        if not provider_error:
            return None

        if isinstance(provider_error, dict):
            error_message = provider_error.get("message", "")
            details = f"{error_message}"

            if error_code := provider_error.get("code"):
                details += f"\nError Code: {error_code}"
            if error_type := provider_error.get("type"):
                details += f"\nError Type: {error_type}"
            if top_level_error:
                details = f"{top_level_error}\n\n{details}"
            return details

        error_msg = str(provider_error)
        if top_level_error:
            return f"{top_level_error}\n\nProvider error: {error_msg}"
        return f"Generation failed. Provider error: {error_msg}"

    def _format_top_level_error(self, top_level_error: Any) -> str:
        """Format error message from top-level error field."""
        if isinstance(top_level_error, dict):
            error_msg = top_level_error.get("message") or top_level_error.get("error") or str(top_level_error)
            return f"Generation failed with error: {error_msg}\n\nFull error details:\n{top_level_error}"
        return f"Generation failed with error: {top_level_error!s}"

    def _set_safe_defaults(self) -> None:
        """Set safe default values for outputs."""
        self.parameter_output_values["generation_id"] = ""
        self.parameter_output_values["provider_response"] = None
        self.parameter_output_values["image_url"] = None

    @staticmethod
    async def _download_bytes_from_url(url: str) -> bytes | None:
        """Download bytes from a URL."""
        try:
            async with httpx.AsyncClient() as client:
                resp = await client.get(url, timeout=120)
                resp.raise_for_status()
                return resp.content
        except Exception:
            return None
