nav:
  - Home: index.md
  - How To:
    - MCP Integration:
      - Overview: how_to/mcp/index.md
      - Getting Started: how_to/mcp/overview.md
      - Using MCPTask with Agents: how_to/mcp/mcp_task_agents.md
      - Use Cases and Workflows: how_to/mcp/use_cases.md
      - Connection Types:
        - Local Process (stdio): how_to/mcp/connection_types/stdio.md
        - Server-Sent Events (SSE): how_to/mcp/connection_types/sse.md
        - Streamable HTTP: how_to/mcp/connection_types/streamable_http.md
        - WebSocket: how_to/mcp/connection_types/websocket.md
      - Popular MCP Servers:
        - Blender: how_to/mcp/servers/blender.md
        - Maya: how_to/mcp/servers/maya.md
        - Brave Search: how_to/mcp/servers/brave.md
        - Slack: how_to/mcp/servers/slack.md
        - Filesystem: how_to/mcp/servers/filesystem.md
        - Memory: how_to/mcp/servers/memory.md
        - Time: how_to/mcp/servers/time.md
        - SQLite: how_to/mcp/servers/sqlite.md
  - Nodes:
    - Lists:
      - Add To List: nodes/lists/add_to_list.md
      - Combine Lists: nodes/lists/combine_lists.md
      - Create List: nodes/lists/create_list.md
      - Display List: nodes/lists/display_list.md
      - Get Index Of Item: nodes/lists/get_index_of_item.md
      - Get From List: nodes/lists/get_from_list.md
      - Get List Contains Item: nodes/lists/get_list_contains_item.md
      - Get List Is Empty: nodes/lists/get_list_is_empty.md
      - Get List Length: nodes/lists/get_list_length.md
      - Remove From List: nodes/lists/remove_from_list.md
      - Replace In List: nodes/lists/replace_in_list.md
      - Split List: nodes/lists/split_list.md
    - Video:
      - Load Video: nodes/video/load_video.md
      - Display Video: nodes/video/display_video.md
      - Save Video: nodes/video/save_video.md
      - Resize Video: nodes/video/resize_video.md
      - Add Film Grain: nodes/video/add_film_grain.md
      - Add RGB Shift: nodes/video/add_rgb_shift.md
      - Add Vignette: nodes/video/add_vignette.md
      - Split Video: nodes/video/split_video.md
      - Adjust Video EQ: nodes/video/adjust_video_eq.md
      - Hold Video Frames: nodes/video/hold_video_frames.md
      - Reverse Video: nodes/video/reverse_video.md
      - Flip Video: nodes/video/flip_video.md 