nav:
  - Home: index.md
  - Nodes:
    - Lists:
      - Add To List: nodes/lists/add_to_list.md
      - Combine Lists: nodes/lists/combine_lists.md
      - Create List: nodes/lists/create_list.md
      - Display List: nodes/lists/display_list.md
      - Get Index Of Item: nodes/lists/get_index_of_item.md
      - Get From List: nodes/lists/get_from_list.md
      - Get List Contains Item: nodes/lists/get_list_contains_item.md
      - Get List Is Empty: nodes/lists/get_list_is_empty.md
      - Get List Length: nodes/lists/get_list_length.md
      - Remove From List: nodes/lists/remove_from_list.md
      - Replace In List: nodes/lists/replace_in_list.md
      - Split List: nodes/lists/split_list.md
    - Video:
      - Load Video: nodes/video/load_video.md
      - Display Video: nodes/video/display_video.md
      - Save Video: nodes/video/save_video.md
      - Resize Video: nodes/video/resize_video.md
      - Add Film Grain: nodes/video/add_film_grain.md
      - Add RGB Shift: nodes/video/add_rgb_shift.md
      - Add Vignette: nodes/video/add_vignette.md
      - Split Video: nodes/video/split_video.md
      - Adjust Video EQ: nodes/video/adjust_video_eq.md
      - Hold Video Frames: nodes/video/hold_video_frames.md
      - Reverse Video: nodes/video/reverse_video.md
      - Flip Video: nodes/video/flip_video.md 