from __future__ import annotations

import json
import logging
from contextlib import suppress
from copy import deepcopy
from typing import Any

from griptape.artifacts.video_url_artifact import VideoUrlArtifact

from griptape_nodes.exe_types.core_types import Parameter, ParameterMode
from griptape_nodes.exe_types.param_components.seed_parameter import SeedParameter
from griptape_nodes.retained_mode.griptape_nodes import GriptapeNodes
from griptape_nodes.traits.options import Options
from griptape_nodes_library.griptape_proxy_node import GriptapeProxyNode

logger = logging.getLogger("griptape_nodes")

__all__ = ["WanTextToVideoGeneration"]

# Define constant for prompt truncation length
PROMPT_TRUNCATE_LENGTH = 100

# Model options with their constraints
MODEL_OPTIONS = [
    "wan2.5-t2v-preview",
    "wan2.2-t2v-plus",
    "wanx2.1-t2v-turbo",
    "wanx2.1-t2v-plus",
]

# Model-specific configurations
MODEL_CONFIGS = {
    "wan2.5-t2v-preview": {
        "sizes": ["480P", "720P", "1080P"],
        "durations": [5, 10],
        "supports_audio": True,
    },
    "wan2.2-t2v-plus": {
        "sizes": ["480P", "720P"],
        "durations": [5],
        "supports_audio": False,
    },
    "wanx2.1-t2v-turbo": {
        "sizes": ["480P", "720P"],
        "durations": [5],
        "supports_audio": False,
    },
    "wanx2.1-t2v-plus": {
        "sizes": ["480P", "720P"],
        "durations": [5],
        "supports_audio": False,
    },
}

# Response status constants
STATUS_FAILED = "Failed"
STATUS_ERROR = "Error"
STATUS_REQUEST_MODERATED = "Request Moderated"
STATUS_CONTENT_MODERATED = "Content Moderated"


class WanTextToVideoGeneration(GriptapeProxyNode):
    """Generate videos from text using WAN models via Griptape model proxy.

    Documentation: https://www.alibabacloud.com/help/en/model-studio/text-to-video-api-reference

    Inputs:
        - model (str): WAN model to use (default: "wan2.5-t2v-preview")
            wan2.5-t2v-preview: Supports 480P/720P/1080P, 5-10s duration, audio
            wan2.2-t2v-plus: Supports 480P/720P, 5s duration
            wanx2.1-t2v-turbo: Supports 480P/720P, 5s duration
            wanx2.1-t2v-plus: Supports 480P/720P, 5s duration
        - prompt (str): Text description of the desired video (max 2000 characters)
        - negative_prompt (str): Description of content to avoid (max 2000 characters)
        - size (str): Output video resolution (model-dependent)
        - duration (int): Video duration in seconds (5 or 10s, model-dependent)
        - prompt_extend (bool): Enable intelligent prompt rewriting (default: False)
        - watermark (bool): Add "Generated by Wan" watermark (default: False)
        - randomize_seed (bool): If true, randomize the seed on each run
        - seed (int): Random seed for reproducible results (default: 42)

    Outputs:
        - generation_id (str): Generation ID from the API
        - provider_response (dict): Verbatim provider response from the model proxy
        - video (VideoUrlArtifact): Generated video as URL artifact
        - was_successful (bool): Whether the generation succeeded
        - result_details (str): Details about the generation result or error
    """

    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        self.category = "API Nodes"
        self.description = "Generate videos from text using WAN models via Griptape model proxy"

        # Model selection
        self.add_parameter(
            Parameter(
                name="model",
                input_types=["str"],
                type="str",
                default_value="wan2.5-t2v-preview",
                tooltip="Select the WAN model to use",
                allowed_modes={ParameterMode.INPUT, ParameterMode.PROPERTY},
                traits={Options(choices=MODEL_OPTIONS)},
            )
        )

        # Prompt parameter
        self.add_parameter(
            Parameter(
                name="prompt",
                input_types=["str"],
                type="str",
                tooltip="Text description of the desired video (max 2000 characters)",
                allowed_modes={ParameterMode.INPUT, ParameterMode.PROPERTY},
                ui_options={
                    "multiline": True,
                    "placeholder_text": "Describe the video you want to generate...",
                    "display_name": "Prompt",
                },
            )
        )

        # Negative prompt parameter
        self.add_parameter(
            Parameter(
                name="negative_prompt",
                input_types=["str"],
                type="str",
                default_value="",
                tooltip="Description of content to avoid (max 2000 characters)",
                allowed_modes={ParameterMode.INPUT, ParameterMode.PROPERTY},
                ui_options={
                    "multiline": True,
                    "placeholder_text": "Describe what you don't want in the video...",
                    "display_name": "Negative Prompt",
                },
            )
        )

        # Size parameter
        self.add_parameter(
            Parameter(
                name="size",
                input_types=["str"],
                type="str",
                default_value="480P",
                tooltip="Output video resolution (available options depend on selected model)",
                allowed_modes={ParameterMode.INPUT, ParameterMode.PROPERTY},
                traits={Options(choices=MODEL_CONFIGS["wan2.5-t2v-preview"]["sizes"])},
            )
        )

        # Duration parameter
        self.add_parameter(
            Parameter(
                name="duration",
                input_types=["int"],
                type="int",
                default_value=5,
                tooltip="Video duration in seconds (5 or 10s, model-dependent)",
                allowed_modes={ParameterMode.INPUT, ParameterMode.PROPERTY},
                traits={Options(choices=[5, 10])},
            )
        )

        # Prompt extend parameter
        self.add_parameter(
            Parameter(
                name="prompt_extend",
                input_types=["bool"],
                type="bool",
                default_value=False,
                tooltip="Enable intelligent prompt rewriting to improve generation quality",
                allowed_modes={ParameterMode.INPUT, ParameterMode.PROPERTY},
            )
        )

        # Watermark parameter
        self.add_parameter(
            Parameter(
                name="watermark",
                input_types=["bool"],
                type="bool",
                default_value=False,
                tooltip="Add 'Generated by Wan' watermark to video",
                allowed_modes={ParameterMode.INPUT, ParameterMode.PROPERTY},
            )
        )

        # Initialize SeedParameter component (at the bottom of input parameters)
        self._seed_parameter = SeedParameter(self)
        self._seed_parameter.add_input_parameters()

        # OUTPUTS
        self.add_parameter(
            Parameter(
                name="generation_id",
                output_type="str",
                tooltip="Generation ID from the API",
                allowed_modes={ParameterMode.OUTPUT},
                ui_options={"hide_property": True},
            )
        )

        self.add_parameter(
            Parameter(
                name="provider_response",
                output_type="dict",
                type="dict",
                tooltip="Verbatim response from Griptape model proxy",
                allowed_modes={ParameterMode.OUTPUT},
                ui_options={"hide_property": True},
            )
        )

        self.add_parameter(
            Parameter(
                name="video",
                output_type="VideoUrlArtifact",
                type="VideoUrlArtifact",
                tooltip="Generated video as URL artifact",
                allowed_modes={ParameterMode.OUTPUT, ParameterMode.PROPERTY},
                settable=False,
                ui_options={"is_full_width": True, "pulse_on_run": True},
            )
        )

        # Create status parameters for success/failure tracking (at the end)
        self._create_status_parameters(
            result_details_tooltip="Details about the video generation result or any errors",
            result_details_placeholder="Generation status and details will appear here.",
            parameter_group_initially_collapsed=False,
        )

    def after_value_set(self, parameter: Parameter, value: Any) -> None:
        """Handle parameter value changes."""
        super().after_value_set(parameter, value)

        # Update parameters when model changes
        if parameter.name == "model" and value in MODEL_CONFIGS:
            model_config = MODEL_CONFIGS[value]

            # Update size choices
            current_size = self.get_parameter_value("size")
            new_sizes = model_config["sizes"]
            if current_size in new_sizes:
                self._update_option_choices("size", new_sizes, current_size)
            else:
                # Set to first available size if current is not supported
                self._update_option_choices("size", new_sizes, new_sizes[0])

            # Update duration choices
            current_duration = self.get_parameter_value("duration")
            new_durations = model_config["durations"]
            if current_duration in new_durations:
                self._update_option_choices("duration", new_durations, current_duration)
            else:
                # Set to first available duration if current is not supported
                self._update_option_choices("duration", new_durations, new_durations[0])

    def _get_api_model_id(self) -> str:
        """Get the API model ID for this generation."""
        return self.get_parameter_value("model") or "wan2.5-t2v-preview"

    async def _build_payload(self) -> dict[str, Any]:
        """Build the request payload for WAN video generation."""
        # Preprocess seed parameter
        self._seed_parameter.preprocess()

        model = self.get_parameter_value("model")
        size = self.get_parameter_value("size")
        duration = self.get_parameter_value("duration")

        # Validate model-specific constraints
        model_config = MODEL_CONFIGS.get(model, MODEL_CONFIGS["wan2.5-t2v-preview"])

        # Validate size
        if size not in model_config["sizes"]:
            msg = f"{model} does not support size {size}. Available sizes: {', '.join(model_config['sizes'])}"
            raise ValueError(msg)

        # Validate duration
        if duration not in model_config["durations"]:
            msg = f"{model} does not support duration {duration}s. Available durations: {', '.join(str(d) for d in model_config['durations'])}s"
            raise ValueError(msg)

        # Build flattened payload (all params at top level)
        payload = {
            "prompt": self.get_parameter_value("prompt"),
            "resolution": size,
            "duration": duration,
            "prompt_extend": self.get_parameter_value("prompt_extend"),
            "watermark": self.get_parameter_value("watermark"),
            "seed": self._seed_parameter.get_seed(),
        }

        # Add negative prompt if provided
        negative_prompt = self.get_parameter_value("negative_prompt")
        if negative_prompt:
            payload["negative_prompt"] = negative_prompt

        # Log request (sanitized)
        self._log_request(payload)

        return payload

    def _log_request(self, payload: dict[str, Any]) -> None:
        """Log request payload with truncated prompt."""
        with suppress(Exception):
            sanitized_payload = deepcopy(payload)
            if "prompt" in sanitized_payload:
                text = sanitized_payload["prompt"]
                if len(text) > PROMPT_TRUNCATE_LENGTH:
                    sanitized_payload["prompt"] = text[:PROMPT_TRUNCATE_LENGTH] + "..."
            logger.info("Request payload: %s", json.dumps(sanitized_payload, indent=2))

    async def _parse_result(self, result_json: dict[str, Any], generation_id: str) -> None:
        """Parse WAN result and save generated video."""
        # Extract video URL from result
        video_url = result_json.get("video_url")
        if not video_url:
            self.parameter_output_values["video"] = None
            self._set_status_results(
                was_successful=False,
                result_details="Generation completed but no video URL was found in the response.",
            )
            return

        # Download and save the video
        try:
            logger.info("Downloading video from URL")
            video_bytes = await self._download_bytes_from_url(video_url)
        except Exception as e:
            logger.error("Failed to download video: %s", e)
            video_bytes = None

        if video_bytes:
            try:
                filename = f"wan_video_{generation_id}.mp4"
                static_files_manager = GriptapeNodes.StaticFilesManager()
                saved_url = static_files_manager.save_static_file(video_bytes, filename)
                self.parameter_output_values["video"] = VideoUrlArtifact(value=saved_url, name=filename)
                logger.info("Saved video to static storage as %s", filename)
                self._set_status_results(
                    was_successful=True, result_details=f"Video generated successfully and saved as {filename}."
                )
            except Exception as e:
                logger.error("Failed to save video: %s", e)
                self.parameter_output_values["video"] = VideoUrlArtifact(value=video_url)
                self._set_status_results(
                    was_successful=True,
                    result_details=f"Video generated successfully. Using provider URL (could not save to static storage: {e}).",
                )
        else:
            self.parameter_output_values["video"] = VideoUrlArtifact(value=video_url)
            self._set_status_results(
                was_successful=True,
                result_details="Video generated successfully. Using provider URL (could not download video bytes).",
            )

    def _extract_error_message(self, response_json: dict[str, Any]) -> str:
        """Extract error message from failed generation response."""
        # Check for WAN-specific error patterns first

        # Check for status-based errors (moderation, failed, etc)
        status = response_json.get("status")
        if status in [STATUS_REQUEST_MODERATED, STATUS_CONTENT_MODERATED]:
            return self._format_moderation_error(response_json)

        if status in [STATUS_FAILED, STATUS_ERROR]:
            result = response_json.get("result", {})
            if isinstance(result, dict) and result.get("error"):
                return f"{self.name} generation failed: {result['error']}"

        # Fall back to standard error extraction
        return super()._extract_error_message(response_json)

    def _format_moderation_error(self, response_json: dict[str, Any]) -> str:
        """Format error message for moderated content."""
        details = response_json.get("details", {})
        moderation_reasons = details.get("Moderation Reasons", [])
        if moderation_reasons:
            reasons_str = ", ".join(moderation_reasons)
            return f"{self.name}: Content was moderated and blocked.\nModeration Reasons: {reasons_str}"
        return f"{self.name}: Content was moderated and blocked by safety filters."

    def _set_safe_defaults(self) -> None:
        """Set safe default values for outputs."""
        self.parameter_output_values["generation_id"] = ""
        self.parameter_output_values["provider_response"] = None
        self.parameter_output_values["video"] = None
